export { default as pluginInterface, validatePlugin } from './plugin-interface.js'
export { api } from './api/http.js'
export { coremgrUrl } from './api/coremgr.js'
export { dataUrl } from './api/data.js'
export { routerUrl } from './api/router.js'
export { useAuth } from './composables/useAuth.js'
export { useConfig } from './composables/useConfig.js'
export { default as sharedMessages } from './i18n/index.js'
